const cabOwners = [
  {
    id: 1,
    name: "Rajesh Sharma",
    email: "rajesh.sharma@example.com",
    phone: "+91 9876543210",
    location: "Delhi",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cabs: [
      {
        id: "cab1",
        model: "Toyota Innova",
        type: "SUV",
        seater: "6-Seater",
        farePerKm: 15,
        dailyFee: 1500,
        rating: 4.8,
        available: true,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
      {
        id: "cab2",
        model: "Maruti Swift",
        type: "Hatchback",
        seater: "4-Seater",
        farePerKm: 10,
        dailyFee: 1000,
        rating: 4.5,
        available: true,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
      {
        id: "cab11",
        model: "Hyundai Verna",
        type: "Sedan",
        seater: "4-Seater",
        farePerKm: 12,
        dailyFee: 1200,
        rating: 4.6,
        available: false,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
    ],
  },
  {
    id: 2,
    name: "Priya Verma",
    email: "priya.verma@example.com",
    phone: "+91 9876543211",
    location: "Mumbai",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cabs: [
      {
        id: "cab3",
        model: "Honda City",
        type: "Sedan",
        seater: "4-Seater",
        farePerKm: 12,
        dailyFee: 1200,
        rating: 4.7,
        available: true,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
      {
        id: "cab4",
        model: "Mahindra Scorpio",
        type: "SUV",
        seater: "7-Seater",
        farePerKm: 18,
        dailyFee: 1800,
        rating: 4.6,
        available: false,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
    ],
  },
  {
    id: 3,
    name: "Amit Patel",
    email: "amit.patel@example.com",
    phone: "+91 9876543212",
    location: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cabs: [
      {
        id: "cab5",
        model: "Hyundai Creta",
        type: "SUV",
        seater: "5-Seater",
        farePerKm: 14,
        dailyFee: 1400,
        rating: 4.8,
        available: true,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
      {
        id: "cab6",
        model: "Tata Tiago",
        type: "Hatchback",
        seater: "4-Seater",
        farePerKm: 9,
        dailyFee: 900,
        rating: 4.4,
        available: true,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
      {
        id: "cab12",
        model: "Volkswagen Virtus",
        type: "Sedan",
        seater: "4-Seater",
        farePerKm: 13,
        dailyFee: 1300,
        rating: 4.7,
        available: false,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
    ],
  },
  {
    id: 4,
    name: "Neha Reddy",
    email: "neha.reddy@example.com",
    phone: "+91 9876543213",
    location: "Hyderabad",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cabs: [
      {
        id: "cab7",
        model: "Kia Seltos",
        type: "SUV",
        seater: "5-Seater",
        farePerKm: 16,
        dailyFee: 1600,
        rating: 4.6,
        available: true,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
      {
        id: "cab8",
        model: "Skoda Superb",
        type: "Luxury",
        seater: "4-Seater",
        farePerKm: 25,
        dailyFee: 2500,
        rating: 4.9,
        available: false,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
    ],
  },
  {
    id: 5,
    name: "Sandeep Singh",
    email: "sandeep.singh@example.com",
    phone: "+91 9876543214",
    location: "Chandigarh",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    cabs: [
      {
        id: "cab9",
        model: "Maruti Ertiga",
        type: "Minivan",
        seater: "7-Seater",
        farePerKm: 13,
        dailyFee: 1300,
        rating: 4.5,
        available: true,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
      {
        id: "cab10",
        model: "Mercedes E-Class",
        type: "Luxury",
        seater: "4-Seater",
        farePerKm: 30,
        dailyFee: 3000,
        rating: 4.9,
        available: false,
        image: "https://c4.wallpaperflare.com/wallpaper/628/480/45/bugatti-bugatti-divo-car-red-car-wallpaper-preview.jpg",
      },
    ],
  },
];

export default cabOwners;
